version: '3.7'
services:
  localstack:
    image: 'localstack/localstack:latest'
    ports: 
      - '4567-4587:4567-4587'
      - '8080:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'